version: '2'
services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wikimedia/wvui
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app
    storybook:
        extends:
            service: node
        ports:
            - '3003:3003'
        command: 'npm start'
